### ISSUE TITLE
Segfault on Ruby 2.2

### ISSUE THREAD

**Issue by nTraum** [railsbp/rails_best_practices#235]
Pardon my ignorance, but is Ruby 2.2 supported already? I'm getting a segfault when running the analyzer on 2.2 (2.1 is fine though).

The stack trace is quite huge, here's a gist: https://gist.github.com/nTraum/3c0c73fb0a7862b3cc01

#### Gem version
```
bundle show | grep rails_best_practices
  * rails_best_practices (1.15.4)
```

#### Rails about
```
bundle exec rake about
About your application's environment
Ruby version             2.2.0-p0 (x86_64-darwin14)
RubyGems version         2.4.5
Rack version             1.5
Rails version            4.1.8
JavaScript Runtime       therubyracer (V8)
Action Pack version      4.1.8
Action View version      4.1.8
Active Support version   4.1.8
Middleware               Rack::Sendfile, ActionDispatch::Static, Rack::Lock, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, RequestStore::Middleware, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions, BetterErrors::Middleware, ActionDispatch::RemoteIp, ActionDispatch::Reloader, ActionDispatch::Callbacks, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ParamsParser, Rack::Head, Rack::ConditionalGet, Rack::ETag, HttpAcceptLanguage::Middleware
Application root         /Users/philipppress/coding/blacklane/aphrodite
Environment              development
```

If you need additionl info, I'm more than happy to help. :ski:

**Comment by oliverklee** [comment]
Do you also get the crash on a pristine default Rails project? Maybe RBP chokes on specific structures/code pieces.

**Comment by nTraum** [comment]
Tested it with vanilla Rails 4.1.9 (+ one scaffolded model), no segfaults.

I also just noticed that I was running `rails_best_practices` in a "weird" rake task looking like this:

```ruby
task :rails_best_practices do
  require "rails_best_practices"
  app_root = Rake.application.original_dir
  analyzer = RailsBestPractices::Analyzer.new(app_root)
  analyzer.analyze
  puts analyzer.output
  fail "found bad practices" if analyzer.runner.errors.size > 0
end
```

Interestingly enough, running `bundle exec rails_best_practices .` from the command line works just fine, so I'll stick to that. Thanks for your help anyway @oliverklee!

Closing this one.

**Comment by McRip** [comment]
I got the same issue, when using rails_best_practices from metric_fu.

**Comment by ShogunPanda** [comment]
Same thing here: only fails from metric_fu

**Comment by dmasur** [comment]
My project fails only on semaphoreci. this doesnt happen on my machine
