### ISSUE TITLE
URL to posts on website broken

### ISSUE THREAD

**Issue by proapi** [railsbp/rails_best_practices#236]
I think that there was some change to the website, and the links from report to posts doesn't work anymore.

For example I get the link from report:
http://rails-bestpractices.com/posts/61-simplify-render-in-views
but the actual site url is:
http://rails-bestpractices.com/posts/2010/12/04/simplify-render-in-views/

As i can see the urls are hardcoded.

**Comment by flyerhzm** [comment]
@proapi fixed
