### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by nTraum** [railsbp/rails_best_practices#240]
Hi,

as a true fan of this gem I welcome noticing the regular updates. What do you think of adding a `CHANGELOG` to the file so people can keep track of all the changes.

Tracking changes is a little complicated right now, you bascially have to check the git log. My update process currently includes just updating blindly and checking if anything is broken (additions of new checks etc).

A good starting point of how to organize / work with a `CHANGELOG` is expained at http://keepachangelog.com/.

WDYT?

**Comment by flyerhzm** [comment]
@nTraum I do agree, just added :-)

**Comment by giedriusr** [comment]
:+1:
