### ISSUE TITLE
--only flag does not work propperly

### ISSUE THREAD

**Issue by dennisvandehoef** [railsbp/rails_best_practices#241]
![bildschirmfoto 2015-03-05 um 13 59 33](https://cloud.githubusercontent.com/assets/7486464/6505216/f981b428-c33f-11e4-9a58-d7c2ea53e41b.png)

wenn running rails_best_practices normally, I get 5 warnings.
but testing the files separately, using the --only flag, it says it's ok.

Since i would like to use rails_best_practices in my pre-push hook, it would be use full and faster if it works all the time ;)
Now it only works most of the time:

![bildschirmfoto 2015-03-05 um 14 03 32](https://cloud.githubusercontent.com/assets/7486464/6505261/73c90894-c340-11e4-9975-2d41c8634578.png)

**Comment by andyw8** [comment]
Which version of the gem are you using?

I'm unable to reproduce this problem in the current release (1.15.7).

**Comment by dennisvandehoef** [comment]
We are using: rails_best_practices (1.15.7)

and the dependencies:

activesupport (4.1.8)
code_analyzer (0.4.5)
colored (1.2)
erubis (2.7.0)
i18n (0.7.0)
json (1.8.2)
require_all (1.3.2)
ruby-progressbar (1.7.1)

**Comment by dennisvandehoef** [comment]
hmmm.. an example of the code that is a problem:

```ruby
    - @cooper_banners.each do |cooper_banner|
      %tr
        %td
          = cooper_banner.name
        %td
          = cooper_banner.product.name
```

The problem is: `cooper_banner.product.name`

In the model, the relation to the product is done with `belongs_to :product`

In my opinion not different from other places where rbp can track the error.

**Comment by dennisvandehoef** [comment]
ok, i have found it, feel like a noob now ;)

it seems that the files in our pre-push hook are "space separated" and not "comma separated"
`parameter_list_rbp=$(echo $relevant_files_rbp | sed -e 's/ /,/g')` did the trick.
