### ISSUE TITLE
--spec ignores model errors

### ISSUE THREAD

**Issue by dankohn** [railsbp/rails_best_practices#242]
Running `rails_best_practices` finds several errors in /app/models. Running `rails_best_practices --spec` does not find any errors.

It would be fine to have a `--spec-only` option that ignore errors outside of the spec directory. But `--spec` is just supposed to 'include spec files', not ignore other errors.

**Comment by flyerhzm** [comment]
@dankohn actually `rails_best_practices` doesn't have any checker for spec directory, so it doesn't make any sense to have a `--spec-only` option.

**Comment by dankohn** [comment]
But then what does `--spec` do? Should it just be removed as an option if all it does is cause errors outside the spec directory to be ignored?

**Comment by flyerhzm** [comment]
@dankohn good question, I may consider to remove this command option.
