### ISSUE TITLE
Haml::TempleEngine: Option :ugly is invalid

### ISSUE THREAD

**Issue by mensfeld** [railsbp/rails_best_practices#291]
Haml::Engine.new(content, {ugly: true}) - it seems, that with new haml engine, the ugly is no longer valid at all

**Comment by mensfeld** [comment]
It seems to occur with haml 5.0.0

**Comment by ryanswood** [comment]
Discussion in Haml project around the removal of the ugly option: https://github.com/haml/haml/pull/894

**Comment by flyerhzm** [comment]
ugly option is removed in version 1.18.1

**Comment by ryanswood** [comment]
@flyerhzm Thank you!
